
name: Build and Test

on:
  push:
    branches: 
      - main
      - ghcr_deploy

  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build-and-test-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make

    - name: Test
      run: make test
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.4.0

    - name: kustomize test
      run: |
        # https://github.com/kubernetes-sigs/kustomize/issues/2867
        kustomize version    
        
    - name: docker build 
      run: make docker-build IMAGE_REGISTRY=ghcr.io/mgaravin/k8s IMAGE_VERSION=main
      
    - name: docker deploy 
      run: |
        make deploy IMAGE_REGISTRY=ghcr.io/mgaravin/k8s IMAGE_VERSION=main
        # getnodes using kubectl
        kubectl get nodes -o wide
      
    - name: docker push
      run: make docker-push IMAGE_REGISTRY=ghcr.io/mgaravin/k8s IMAGE_VERSION=main
