name: HadolintTest

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:

  HadolintTest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: ghcr.io/hadolint/hadolint
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: hadolint/hadolint-action@v2.1.0
        
    - name: test all dockerfiles
      run: | 
        find . -name Dockerfile* -exec \
        sh -c 'src=${1#./} && { set -x && hadolint "$1"; } | tee -a "reports/${src%%/*}.txt"' sh "{}" \;
