name: Build and Test

on:
  push:
    branches:
      - main
      - github-permissions

  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:


  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: change persmissions
      run: |
        sudo chmod 775 -R /var/lib/cni
        ls -ltr /var/lib/cni
