name: Build and Test

on:
  push:
    branches: 
      - main
      - deploy_test

  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build-and-test-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: make

    - name: Test
      run: make test
      
    - name: deploy
      run: make all
