name: HadolintTest

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:

  HadolintTest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    
    - uses: actions/checkout@v3

    - uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: images/Dockerfile.agent
        recursive: false
        no-color: true
        no-fail: true
        verbose: true
        format: tty
        failure-threshold: info
